{% set name = "django-grpc" %}
{% set version = "1.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/django_grpc-{{ version }}.tar.gz
  sha256: eb80b1e5dcf855f421ffd363571cecd592ea298a5dbbc8b6b7306288cac81d3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - setuptools
    - django >=4.2,<7.0
    - protobuf
    - grpcio
    - grpcio-tools
    - grpcio-reflection

test:
  imports:
    - django_grpc
    - django_grpc_testtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gluk-w/django-grpc
  summary: Easy Django based gRPC service
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - pb01ka
